GET cdn.kickbase.com/files/users/2979455/0

###
GET /files/users/2979455/0
Host: cdn.kickbase.com
Content-Type: application/json
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrYi5uYW1lIjoiQW5vIiwia2IudWlkIjoiMjgyNzQyNiIsImtiLnIiOiIyIiwia2IuYSI6IjIiLCJrYi5wIjoiIiwiaWF0IjoxNzAzNTAyNTk1LCJuYmYiOjE3MDM1MDI1OTUsImV4cCI6MTcwNDEwNzM5NSwiaXNzIjoiaHR0cDovL2tpY2tiYXNlLmNvbSIsImF1ZCI6ImtpY2tiYXNlIn0.zicbTfUoglD1qvVOvCEq-AZBV_yTQ4S_lsdwHTokEu8

###
GET /files/teams/6541/11
Host: cdn.kickbase.com
Content-Type: application/json
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrYi5uYW1lIjoiQW5vIiwia2IudWlkIjoiMjgyNzQyNiIsImtiLnIiOiIyIiwia2IuYSI6IjIiLCJrYi5wIjoiIiwiaWF0IjoxNzAzNTAyNTk1LCJuYmYiOjE3MDM1MDI1OTUsImV4cCI6MTcwNDEwNzM5NSwiaXNzIjoiaHR0cDovL2tpY2tiYXNlLmNvbSIsImF1ZCI6ImtpY2tiYXNlIn0.zicbTfUoglD1qvVOvCEq-AZBV_yTQ4S_lsdwHTokEu8
