### Login
POST /user/login HTTP/1.1
Host: api.kickbase.com
Content-Type: application/json
Accept: application/json

{
    "email": "antje.kasemann@gmail.com",
    "password": "Pkn93Q3upPCjGss",
    "ext": false
}


### Reset Password
POST /user/resetpassword HTTP/1.1
Host: api.kickbase.com
Content-Type: application/json
Accept: application/json

{
    "password": "",
    "token": ""
}


### League User Info
GET /leagues/[league_id]/me HTTP/1.1
Host: api.kickbase.com
Content-Type: application/json
Accept: application/json
Cookie: kkstrauth=[token];


### User Match Day Feed
GET /leagues/[league_id]/users/[user_id]/feed HTTP/1.1
Host: api.kickbase.com
Content-Type: application/json
Accept: application/json
Cookie: kkstrauth=[token];


### Refresh Chat Token
POST /user/refreshchattoken HTTP/1.1
Host: api.kickbase.com
Content-Type: application/json
Accept: application/json
Cookie: kkstrauth=[token];